name: CI
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        cache: [true, false]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./
        with:
          cache-enabled: ${{ matrix.cache }}
          cache-key: texlive-${{ github.job_id }}-${{ matrix.os }}
          packages-path: ${{ github.workspace }}/.github/texlive.packages
          profile-path: ${{ github.workspace }}/.github/texlive.profile
      - name: Test tlmgr availability
        run: tlmgr version
      - name: Test run for latex
        run: latex small2e
      - name: Test run from pdflatex
        run: pdflatex sample2e
